### ISSUE TITLE
Code improvements

### ISSUE THREAD

**Issue by bglowacki** [Chri5At/soil_moisture_sensors_for_esp_home#2]
Hey!
Got some code improvements ideas. Happy to share:

Instead of using script for enabling or preventing deep sleep you could use something like this

```
text_sensor:
  - platform: homeassistant
    entity_id: input_boolean.prevent_deep_sleep_soil_moisture
    id: prevent_deep_sleep
    on_value: 
      then:
        - if: 
            condition:
              text_sensor.state: 
                id: prevent_deep_sleep
                state: "on"
            then: 
              - logger.log: "Preventing deep sleep"
              - deep_sleep.prevent: deep_sleep_enabled
            else: 
              - logger.log: "Deep sleep enabled"
              - deep_sleep.allow: deep_sleep_enabled
```

With this you could move all the updates to on_boot callback and use on_shutdown to make sure to disable the GPIO on sleep:

```
  on_boot: 
    priority: -100
    then:
      - wait_until: 
          condition:
            api.connected
      - output.turn_on: gpio_sensor
      - delay: 10s
      - component.update: soil_moisture_raw
      - component.update: battery_voltage
      - delay: 5s
      - component.update: soil_moisture
      - component.update: battery_percentage
  on_shutdown: 
    then:
      - output.turn_off: gpio_sensor
      - delay: 5s
```

All those delays are "just in case". I'm not sure if they are needed

**Comment by Chri5At** [comment]
Hey.
Thanks for sharing =). Very nice - the code is way cleaner.

I'm currently having troubles with the ESP32 C6 - the uC sometimes does not enter deep sleep. 
![2024_11_05 ESP32 C6 Deep Sleep Fails](https://github.com/user-attachments/assets/12b81419-b3ec-45d7-9a75-98d57f29d9b6)

So your suggestions comes at the perfect time. I updated the yaml with your code and added the following line to your `text_sensor` - block: `- deep_sleep.enter: deep_sleep_enabled`
Otherwise, the uC doesn't enter deep sleep
![text_sensor](https://github.com/user-attachments/assets/e5448515-014e-4a12-857a-cb239137df73)

I let it run for a while, but when i looked at battery consumption it seemed, the uC did not resume from deep sleep reliable
![2024_11_05 ESP32 C6 New code without script 1](https://github.com/user-attachments/assets/c41ae585-a11c-4725-b351-52ab5555007d)

At the end this was my bad because the "up time" is now much shorter and my sampling rate on the INA3221 board is too slow. When checking the actual values delivered by the C6 - everything is fine
![2024_11_05 ESP32 C6 New code without script 2](https://github.com/user-attachments/assets/17ce8b6a-493d-45eb-b5a8-ba8d806edfc6)

Here are the according code snippets
```
  on_boot: 
    priority: -100
    then:
      - wait_until: 
          condition:
            api.connected
      - delay: 2s
      - output.turn_on: gpio_sensor
      - delay: 10s
      - component.update: esp_c6_2nd_battery_voltage
      - component.update: esp_c6_2nd_battery_level
      - component.update: esp_c6_2nd_moisture_value
      - component.update: c6_2nd_wifi_signal_db
  on_shutdown: 
    then:
      - output.turn_off: gpio_sensor
      - delay: 3s
```

```      
text_sensor:
  - platform: homeassistant
    entity_id: input_boolean.sms_esps_prevent_deep_sleep
    id: prevent_deep_sleep
    on_value: 
      then:
        - if: 
            condition:
              text_sensor.state: 
                id: prevent_deep_sleep
                state: "on"
            then: 
              - logger.log: "Preventing deep sleep"
              - deep_sleep.prevent: deep_sleep_enabled
            else: 
              - logger.log: "Deep sleep enabled"
              - deep_sleep.allow: deep_sleep_enabled
              - deep_sleep.enter: deep_sleep_enabled
```
              
I'm curious if your solution fixes the deep sleep problem. We will know tomorrow - I'll keep you updated.

Many thanks for your contribution!!

**Comment by gs-bglowacki** [comment]
You did all the hardwork :D

My current setup looks like this. And I don't have any problems with it entering the deep sleep

One thing I noticed is that after setting up the helper in homeassistant you must at least once change it's state so that esphome can pick it up.

```
esphome:
  name: testing
  friendly_name: testing
  on_boot: 
    priority: -100
    then:
      - wait_until: 
          condition:
            api.connected
      - output.turn_on: gpio_sensor
      - delay: 100ms
      - component.update: battery_voltage_raw
      - delay: 100ms
      - component.update: battery
      - delay: 100ms
      - component.update: soil_moisture_raw
      - delay: 100ms
      - component.update: soil_moisture
      - delay: 100ms
      - component.update: wifi_signal_db
      - delay: 100ms
      - component.update: wifi_signal_percentage
      - delay: 100ms
      - if: 
          condition:
            - text_sensor.state: 
                id: prevent_deep_sleep
                state: "off"
          then: 
            - deep_sleep.enter: deep_sleep_enabled
  
  on_shutdown: 
    then:
      - output.turn_off: gpio_sensor

esp32:
  board: firebeetle32
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: 

ota:
  - platform: esphome
    password: 

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Testing Fallback Hotspot"
    password: 

captive_portal:

deep_sleep:
  id: deep_sleep_enabled
  run_duration: 
    seconds: 20
  sleep_duration: 
    minutes: 60
output:
  - platform: gpio
    pin: GPIO26
    id: gpio_sensor
    inverted: False

text_sensor:
  - platform: homeassistant
    entity_id: input_boolean.prevent_deep_sleep_soil_moisture
    id: prevent_deep_sleep
    on_value: 
      then:
        - if: 
            condition:
              text_sensor.state: 
                id: prevent_deep_sleep
                state: "on"
            then: 
              - logger.log: "Preventing deep sleep"
              - deep_sleep.prevent: deep_sleep_enabled
            else: 
              - logger.log: "Deep sleep enabled"
              - deep_sleep.allow: deep_sleep_enabled

sensor:
  - platform: adc
    pin: GPIO36
    id: battery_voltage_raw
    device_class: battery
    accuracy_decimals: 5
    name: Battery Voltage Raw
    force_update: True
    attenuation: 12dB
    entity_category: diagnostic
    filters: 
      - multiply: 2
  - platform: template
    accuracy_decimals: 0
    id: battery
    device_class: battery
    entity_category: diagnostic
    force_update: True
    name: Battery
    unit_of_measurement: "%"
    lambda: |-
      return id(battery_voltage_raw).state;
    filters:
      - calibrate_polynomial:
          degree: 2
          datapoints: 
            - 2.5 -> 0
            - 3.0 -> 10
            - 3.2 -> 20
            - 3.4 -> 30
            - 3.5 -> 40
            - 3.6 -> 50
            - 3.7 -> 60
            - 3.8 -> 70
            - 3.9 -> 80
            - 4.0 -> 90
            - 4.2 -> 100
      - clamp:
          min_value: 0
          max_value: 100
      
  
  - platform: wifi_signal # Reports the WiFi signal strength/RSSI in dB
    name: "WiFi Signal dB"
    id: wifi_signal_db
    update_interval: 60s
    entity_category: diagnostic

  - platform: template # Reports the WiFi signal strength in %
    name: "WiFi Signal Percent"
    id: wifi_signal_percentage
    lambda: |-
      return id(wifi_signal_db).state;
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "%"
    entity_category: diagnostic
    device_class: signal_strength

  - platform: adc
    pin: GPIO35
    id: soil_moisture_raw
    name: Wilgotność V
    state_class: measurement
    attenuation: 12db
    accuracy_decimals: 2
    force_update: True
  - platform: template
    accuracy_decimals: 0
    id: soil_moisture
    device_class: moisture
    name: Wilgotność %
    unit_of_measurement: "%"
    force_update: True
    lambda: |-
      return id(soil_moisture_raw).state;
    filters: 
      - calibrate_linear:
        - 2.56300 -> 0.00
        - 1.22500 -> 100.00
      - clamp:
          min_value: 0
          max_value: 100
          ignore_out_of_range: true
```

Let me know about your findings for c6. As I remember it can use zigbee right?
